### ISSUE TITLE
app.engine("handlebars", engine()); error

### ISSUE THREAD

**Issue by phineasla** [express-handlebars/express-handlebars#248] opened 2021-11-29 08:49 UTC
Hi, I have some trouble setting up while using Express + Typescript
```
Argument of type 'Engine' is not assignable to parameter of type '(path: string, options: object, callback: (e: any, rendered?: string | undefined) => void) => void'.
  Types of parameters 'options' and 'options' are incompatible.
    Type 'object' is not assignable to type 'EngineOptions'.
      Index signature for type 'string' is missing in type '{}'.
```
The code is the same in Usage:
```
import express from 'express';
import { engine } from 'express-handlebars';

const app = express();

app.engine('handlebars', engine());
app.set('view engine', 'handlebars');
```

**Comment by UziTech** [comment] 2021-11-29 14:33
Duplicate of #240. Should be fixed in the latest version.

**Closed by UziTech** 2021-11-29 14:33 UTC
